### ISSUE TITLE
can you track an address (no staking addr associated) for new transaction and send a notification to the telegram bot?

### ISSUE THREAD

**Issue by shinrajunn** [DevStakePool/thoth-bot#11]
can you track a smart contract address without a stake key?

**Comment by DevStakePool** [comment]
Hi, could you be more precise? I have access to all the blockchain information from the bot

**Comment by shinrajunn** [comment]
addr1wxwrp3hhg8xdddx7ecg6el2s2dj6h2c5g582yg2yxhupyns8feg4m would like to track this address, each time there is a new transaction, i hope i can get a notification on telegram. can you even just track input?

**Comment by DevStakePool** [comment]
I see, because you don't have a registered staking address related to that. In that case, I'll add this feature so that you can register the address instead of the staking address. I'll try to add this feature soon. Thanks for the suggestion!

**Comment by DevStakePool** [comment]
Major refactoring work started. There are quite some changes to apply, identified by the `FIXME 11` comments

**Comment by DevStakePool** [comment]
Merged to dev
