### ISSUE TITLE
Implement DReps notifications

### ISSUE THREAD

**Issue by slux83** [DevStakePool/thoth-bot#52]
some notes
- to perform every 1h or so..
- wallets that are registered to a drep using https://api.koios.rest/#post-/account_info_cached
- process in batches all accounts that have the drep.
- gather drep votes (cach it) using https://api.koios.rest/#get-/drep_votes (unfortunately one by one this is why cashing is important)
- show the user the link to gather information about the gov action (for that use the https://api.koios.rest/#get-/proposal_list or any website when available maybe https://gov.tools/connected/governance_actions/7fd6429add8f2611ad8d48c0cc49101463093aec285faea402e8cfde78ea58d7#0) that hash is the proposal_tx_hash. So easier to use that so you don't have to parse the external URLs

**Comment by DevStakePool** [comment]
That's how it looks like
![image](https://github.com/user-attachments/assets/3cff25d4-adad-4cdf-ac54-8315ececc573)
